services:
  neo4j:
    image: neo4j:5.18.1
    container_name: neo4j_nsdmg
    ports:
      - "7474:7474" # HTTP port for Neo4j Browser
      - "7687:7687" # Bolt port
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  graphcortex:
    build: .
    container_name: graphcortex_swarm
    tty: true
    stdin_open: true
    depends_on:
      neo4j:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
      - ./Logs:/app/Logs
      - ./data:/app/data
